# Generated by Django 5.2.5 on 2025-09-25 11:53

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityhub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='hub_post_search_gin',
        ),
        migrations.RemoveIndex(
            model_name='thread',
            name='hub_thread_search_gin',
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='hub_post_search_gin'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_document'], name='hub_thread_search_gin'),
        ),
    ]
