# Generated by Django 5.2.5 on 2025-10-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityhub', '0004_fix_gin_index_operator_class'),
    ]

    operations = [
        # Add performance indexes for frequently queried fields
        migrations.RunSQL(
            # Create indexes for channel memberships
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_channel_memberships_user_active ON communityhub_channelmembership (user_id, is_active) WHERE is_active = true;",
            reverse_sql="DROP INDEX IF EXISTS idx_channel_memberships_user_active;"
        ),
        migrations.RunSQL(
            # Create index for posts by channel and creation date
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_posts_channel_created ON communityhub_post (channel_id, created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_posts_channel_created;"
        ),
        migrations.RunSQL(
            # Create index for threads by channel, pinned status, and creation date
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_threads_channel_pinned ON communityhub_thread (channel_id, is_pinned, created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_threads_channel_pinned;"
        ),
        migrations.RunSQL(
            # Create index for posts by thread and creation date
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_posts_thread_created ON communityhub_post (thread_id, created_at DESC);",
            reverse_sql="DROP INDEX IF EXISTS idx_posts_thread_created;"
        ),
        migrations.RunSQL(
            # Create index for channel memberships by channel and active status
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_channel_memberships_channel_active ON communityhub_channelmembership (channel_id, is_active) WHERE is_active = true;",
            reverse_sql="DROP INDEX IF EXISTS idx_channel_memberships_channel_active;"
        ),
    ]
