# Generated by Django 5.2.5 on 2025-09-05 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, help_text="User's profile picture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='wagtailimages.image', verbose_name='Avatar'),
        ),
    ]
